article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    path('increase-likes/<int:id>/', views.increase_likes, name='increase_likes'),
]

diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('diary-list/', views.diary_list, name='diary_list'),
    path('diary-detail/<int:id>/', views.diary_detail, name='diary_detail'),
    path('diary-create/', views.diary_create, name='diary_create'),
    path('diary-safe-delete/<int:id>/', views.diary_safe_delete, name='diary_safe_delete'),
    path('diary-update/<int:id>/', views.diary_update, name='diary_update'),
]

doc/urls.py
from django.urls import path
from . import views

app_name = 'doc'

urlpatterns = [
    path('folder-list/', views.folder_list, name='folder_list'),
    path('folder-create/', views.folder_create, name='folder_create'),
    path('folder-delete/<int:id>/', views.folder_delete, name='folder_delete'),
    path('doc-list/<int:folder>', views.doc_list, name='doc_list'),
    path('doc-add/', views.doc_add, name='doc_add'),
    path('doc-delete/<int:id>/', views.doc_delete, name='doc_delete'),
    path('doc-download/<int:id>', views.doc_download, name='doc_download'),
]

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('logout/', views.user_logout, name='logout'),
    path('switch/', views.user_switch, name='switch'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
    path('check-username/', views.check_username, name='check_username'),
    path('check-password1/', views.check_password1, name='check_password1'),
    path('check-password2/', views.check_password2, name='check_password2'),
    path('check-email/', views.check_email, name='check_email'),
    path('user-login-check/', views.user_login_check, name='user_login_check'),
]

templates/back_to_top_func.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
          crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>
<!-- 引入导航栏 -->
{% include 'header.html' %}
<!-- 预留具体页面的位置 -->
{% block content %}{% endblock content %}
<script src="{% static 'jquery/jquery.js' %}"></script>
<script src="{% static 'popper/popper.js' %}"></script>
<!-- 引入bootstrap的js文件 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'layer/layer.js' %}"></script>
{% block script %}{% endblock script %}
{% include 'back_to_top_func.html' %}
</body>

</html>

templates/header.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="/">我的博客</a>

        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
            </li>
            <li class="nav-item">
                {% if user.is_superuser %}
                    <a class="nav-link" href="{% url 'diary:diary_list' %}">日记</a>
                {% else %}
                    <a class="nav-link" href="#" onclick="warning()">日记</a>
                {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'photologue:gallery-list' %}">相册</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'doc:folder_list' %}">文件</a>
            </li>
        </ul>


        <div>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <!-- 如果用户已经登录，则显示用户名下拉框 -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if unread_count %}
                                <svg viewBox="0 0 8 8"
                                     width="8px"
                                     height="8px">
                                    <circle cx="4"
                                            cy="4"
                                            r="4"
                                            fill="#ff6b6b"
                                    ></circle>
                                </svg>
                            {% endif %}
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url "notice:list" %}">通知
                                {% if unread_count %}
                                    <span class="badge badge-danger">{{ unread_count }}</span>
                                {% endif %}
                            </a>
                            {#                         {% if user.is_superuser %}#}
                            {#                            <a class="dropdown-item" href="{% url 'article:article_create' %}">写文章</a>#}
                            {#                         {% endif %}#}
                            <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
                            <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                            <a class="dropdown-item" href="{% url "userprofile:switch" %}">切换账号</a>
                            <a class="dropdown-item" href="{% url "userprofile:logout" %}">退出登录</a>
                        </div>
                    </li>
                    <!-- 如果用户未登录，则显示 “登录” -->
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/login/">登录</a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>


{% if user.is_authenticated %}
    <form
            style="display:none;"
            id="user_delete"
            action="{% url 'userprofile:delete' user.id %}"
            method="POST"
    >
        {% csrf_token %}
        <button type="submit">发送</button>
    </form>
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除用户吗？",
                yes: function (index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}


<script>
    function warning() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "权限不够",
            // 正文
            content: "您无权查看此栏目",
            // 点击确定按钮后调用的回调函数
            yes: function (index, layero) {
                layer.close(index);
            },
        })
    }
</script>


{#<script>#}
{#    function info() {#}
{#        // 调用layer弹窗组件#}
{#        layer.open({#}
{#            // 弹窗标题#}
{#            title: "消息",#}
{#            // 正文#}
{#            content: "施工中！",#}
{#            // 点击确定按钮后调用的回调函数#}
{#            yes: function (index, layero) {#}
{#                layer.close(index);#}
{#            },#}
{#        })#}
{#    }#}
{#</script>#}