article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    path('increase-likes/<int:id>/', views.increase_likes, name='increase_likes'),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    path('post-comment/<int:article_id>', views.post_comment, name='post_comment'),
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply')
]

doc/urls.py
from django.urls import path
from . import views

app_name = 'doc'

urlpatterns = [
    path('folder-list/', views.folder_list, name='folder_list'),
    path('folder-create/', views.folder_create, name='folder_create'),
    path('folder-delete/<int:id>/', views.folder_delete, name='folder_delete'),
    path('doc-list/<int:folder>', views.doc_list, name='doc_list'),
    path('doc-add/', views.doc_add, name='doc_add'),
    path('doc-delete/<int:id>/', views.doc_delete, name='doc_delete'),
    path('doc-download/<int:id>', views.doc_download, name='doc_download'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.

class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)
    total_views = models.PositiveIntegerField(default=0)
    # 文章标签
    tags = TaggableManager(blank=True)
    likes = models.PositiveIntegerField(default=0)

    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

article/forms.py
from django import forms
from .models import ArticlePost

# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body', 'tags')

article/views.py
from django.shortcuts import render, redirect
from .models import ArticlePost
from django.http import HttpResponse
from .forms import ArticlePostForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from comment.models import Comment
from comment.forms import CommentForm
import markdown
# Create your views here.

def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    tag = request.GET.get('tag')

    article_list = ArticlePost.objects.all()

    # 搜索查询集
    if search:
        article_list = article_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search = ''


    # 标签查询集
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

    # 查询集排序
    if order == 'total_views':
        article_list = article_list.order_by('-total_views')

    paginator = Paginator(article_list, 10)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    # 需要传递给模板（templates）的对象
    context = {
        'articles': articles,
        'order': order,
        'search': search,
        'tag': tag,
    }

    return render(request, 'article/list.html', context)


def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    comments = Comment.objects.filter(article=id)

    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )
    article.body = md.convert(article.body)

    # 浏览量 +1
    article.total_views += 1
    article.save(update_fields=['total_views'])

    comment_form = CommentForm()
    context = {'article': article, 'toc': md.toc, 'comments': comments, 'comment_form': comment_form,}
    return render(request, 'article/detail.html', context)

@login_required(login_url='/accounts/login/')
def article_create(request):
    superuser = User.objects.get(is_superuser=True)
    if request.user != superuser:
        return HttpResponse("抱歉，你无权写文章。")
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            new_article.save()
            # 保存 tags 的多对多关系
            article_post_form.save_m2m()
            return redirect("article:article_list")
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        article_post_form = ArticlePostForm()
        context = {'article_post_form': article_post_form}
        return render(request, 'article/create.html', context)

@login_required(login_url='/accounts/login/')
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        # 过滤非作者的用户
        if request.user != article.author:
            return HttpResponse("抱歉，你无权修改这篇文章。")
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("仅允许post请求")

@login_required(login_url='/accounts/login/')
def article_update(request, id):
    article = ArticlePost.objects.get(id=id)
    # 过滤非作者的用户
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            # 保存新写入的 title、body 数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            # 完成后返回到修改后的文章中。需传入文章的 id 值
            return redirect("article:article_detail", id=id)
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        context = {'article': article}
        return render(request, 'article/update.html', context)


def increase_likes(request, id):
    if request.method == "POST":
        article = ArticlePost.objects.get(id=id)
        article.likes += 1
        article.save()
        return HttpResponse('success')

templates/article/create.html
{% extends "base.html" %}
{% block title %} 写文章 {% endblock title %}

{% block content %}
    <!-- 写文章表单 -->
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <!-- 提交文章的表单 -->
                <form method="post" action=".">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">文章标题</label>
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                    <!-- 文章标签 -->
                    <div class="form-group">
                        <label for="tags">标签</label>
                        <input type="text"
                               class="form-control col-3"
                               id="tags"
                               name="tags"
                        >
                    </div>
                    <!-- 文章正文 -->
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        <!-- 文本区域 -->
                        <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/article/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    文章详情
{% endblock title %}

{% block content %}

    <!-- 文章详情 -->
    <div class="container">
        <div class="row">
            <!-- 标题及作者 -->
            <div class="col-9">
                <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
                <div class="col-12 alert alert-success">作者：{{ article.author }}
                    {% if user == article.author %}
                        <a href="{% url "article:article_update" article.id %}">编辑文章</a>
                        <a href="#" class="text-danger" onclick="confirm_delete()">删除文章</a>
                        {#表单携带csrf令牌发起POST请求#}
                        <form
                                style="display:none;"
                                id="safe_delete"
                                action="{% url 'article:article_safe_delete' article.id %}"
                                method="POST"
                        >
                            {% csrf_token %}
                            <button type="submit">发送</button>
                        </form>

                    {% endif %}
                    <div>
                        浏览：{{ article.total_views }}
                    </div>
                    <div>
                        最后编辑于：{{ article.updated|date:"Y-m-d H:i" }}
                    </div>
                </div>
                <!-- 文章正文 -->
                <div class="col-12">
                    <p>{{ article.body|safe }}</p>
                </div>

                <!-- 点赞按钮 -->
                <div style="text-align:center;" class="mt-4">
                    <button class="btn btn-outline-danger"
                            type="button"
                            onclick="validate_is_like(
                                    '{% url 'article:increase_likes' article.id %}',
                                    {{ article.id }},
                                    {{ article.likes }}
                                    )"
                    >
                        <span>点赞</span>
                        <span>
                    <i class="fas fa-heart"></i>
                </span>
                        <span id="likes_number">
                    {{ article.likes }}
                </span>
                    </button>
                </div>


                <!-- 发表评论 -->
                <hr>
                {% if user.is_authenticated %}
                    <div>
                        <form
                                action="{% url 'comment:post_comment' article.id %}"
                                method="POST"
                        >
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="body">
                                    <strong>
                                        我也要发言：
                                    </strong>
                                </label>
                                {#                    <textarea#}
                                {#                        type="text"#}
                                {#                        class="form-control"#}
                                {#                        id="body"#}
                                {#                        name="body"#}
                                {#                        rows="2"></textarea>#}
                                <div>
                                    {{ comment_form.media }}
                                    {{ comment_form.body }}
                                </div>
                            </div>
                            <!-- 提交按钮 -->
                            <button type="submit" class="btn btn-primary ">发送</button>
                        </form>
                    </div>
                    <br>
                {% else %}
                    <br>
                    <h5 class="row justify-content-center">
                        请<a href="{% url 'account_login' %}">登录</a>后回复
                    </h5>
                    <br>
                {% endif %}



                <!-- 显示评论 -->
                {% load mptt_tags %}
                <h4>共有{{ comments.count }}条评论</h4>
                <div class="row">
                    <!-- 遍历树形结构 -->
                    {% recursetree comments %}
                        <!-- 给 node 取个别名 comment -->
                        {% with comment=node %}
                            <div class="{% if comment.reply_to %}
                        offset-1 col-11
                        {% else %}
                        col-12
                        {% endif %}"
                            >
                                <hr>
                                <p>
                                    <strong style="color: pink">
                                        {{ comment.user }}
                                    </strong>

                                    {% if comment.reply_to %}
                                        <i class="far fa-arrow-alt-circle-right"
                                           style="color: cornflowerblue;"
                                        ></i>
                                        <strong style="color: pink">
                                            {{ comment.reply_to }}
                                        </strong>
                                    {% endif %}

                                </p>
                                <div>{{ comment.body|safe }}</div>

                                <div>
                    <span style="color: gray">
                        {{ comment.created|date:"Y-m-d H:i" }}
                    </span>

                                    <!-- 加载 modal 的按钮 -->
                                    {% if user.is_authenticated %}
                                        <button type="button"
                                                class="btn btn-light btn-sm text-muted"
                                                onclick="load_modal({{ article.id }}, {{ comment.id }})"
                                        >
                                            回复
                                        </button>
                                    {% else %}
                                        <a class="btn btn-light btn-sm text-muted"
                                           href="{% url 'account_login' %}"
                                        >
                                            回复
                                        </a>
                                    {% endif %}
                                </div>

                                <!-- Modal -->
                                <div class="modal fade"
                                     id="comment_{{ comment.id }}"
                                     tabindex="-1"
                                     role="dialog"
                                     aria-labelledby="CommentModalCenter"
                                     aria-hidden="true"
                                >
                                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                        <div class="modal-content" style="height: 480px">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalCenterTitle">
                                                    回复 {{ comment.user }}：</h5>
                                            </div>
                                            <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                        </div>

                                    </div>
                                </div>

                                {% if not comment.is_leaf_node %}
                                    <div class="children">
                                        {{ children }}
                                    </div>
                                {% endif %}
                            </div>


                        {% endwith %}
                    {% endrecursetree %}
                </div>


            </div>
            <div class="col-3 mt-4">
                <h4><strong>目录</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}


{% block script %}
    <script src="{% static 'csrf.js' %}"></script>

    <script>
        $(".django-ckeditor-widget").removeAttr('style');
    </script>

    <script>
        function confirm_delete() {
            // 调用layer弹窗组件
            layer.open({
                // 弹窗标题
                title: "确认删除",
                // 正文
                content: "确认删除这篇文章吗？",
                // 点击确定按钮后调用的回调函数
                yes: function (index, layero) {
                    $('form#safe_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>

    <script>
        // 加载 modal
        function load_modal(article_id, comment_id) {
            let modal_body = '#modal_body_' + comment_id;
            let modal_id = '#comment_' + comment_id;

            // 加载编辑器
            if ($(modal_body).children().length === 0) {
                let content = '<iframe src="/comment/post-comment/' +
                    article_id +
                    '/' +
                    comment_id +
                    '"' +
                    ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' +
                    comment_id +
                    '"></iframe>';
                $(modal_body).append(content);
            }
            ;

            $(modal_id).modal('show');
        }
    </script>


    <script>
        // 点赞功能主函数
        function validate_is_like(url, id, likes) {
            // 取出 LocalStorage 中的数据
            let storage = window.localStorage;
            const storage_str_data = storage.getItem("my_blog_data");
            let storage_json_data = JSON.parse(storage_str_data);
            // 若数据不存在，则创建空字典
            if (!storage_json_data) {
                storage_json_data = {}
            }
            ;
            // 检查当前文章是否已点赞。是则 status = true
            const status = check_status(storage_json_data, id);
            if (status) {
                layer.msg('已经点过赞了哟~');
                // 点过赞则立即退出函数
                return;
            } else {
                // 用 Jquery 找到点赞数量，并 +1
                $('span#likes_number').text(likes + 1).css('color', '#dc3545');
            }
            // 用 ajax 向后端发送 post 请求
            $.post(
                url,
                // post 只是为了做 csrf 校验，因此数据为空
                {},
                function (result) {
                    if (result === 'success') {
                        // 尝试修改点赞数据
                        try {
                            storage_json_data[id] = true;
                        } catch (e) {
                            window.localStorage.clear();
                        }
                        ;
                        // 将字典转换为字符串，以便存储到 LocalStorage
                        const d = JSON.stringify(storage_json_data);
                        // 尝试存储点赞数据到 LocalStorage
                        try {
                            storage.setItem("my_blog_data", d);
                        } catch (e) {
                            // code 22 错误表示 LocalStorage 空间满了
                            if (e.code === 22) {
                                window.localStorage.clear();
                                storage.setItem("my_blog_data", d);
                            }
                        }
                        ;
                    } else {
                        layer.msg("与服务器通信失败..过一会儿再试试呗~");
                    }

                }
            );
        };

        // 辅助点赞主函数，验证点赞状态
        function check_status(data, id) {
            // 尝试查询点赞状态
            try {
                if (id in data && data[id]) {
                    return true;
                } else {
                    return false;
                }
            } catch (e) {
                window.localStorage.clear();
                return false;
            }
            ;
        };
    </script>

{% endblock script %}

templates/article/list.html
{% extends "base.html" %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

    <!-- 定义放置文章标题的div容器 -->
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'article:article_list' %}?search={{ search }}&tag={{ tag }}">最新</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'article:article_list' %}?order=total_views&search={{ search }}&tag={{ tag }}">热门</a>
                    </li>
                </ul>

            </div>
            <form class="navbar-form">
                <label class="sr-only">content</label>
                <input type="text"
                       class="form-control"
                       name="search"
                       placeholder="搜索文章..."
                       required
                >
            </form>

            <ul class="navbar-nav ml-3">
                <li class="nav-item ml-auto">
                    {% if user.is_superuser %}
                        <a class="btn btn-primary" href="{% url 'article:article_create' %}">写文章</a>
                    {% endif %}
                </li>
            </ul>
        </nav>

        <!-- 搜索提示语 -->
        {% if search %}
            {% if articles %}
                <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
                <hr>
            {% else %}
                <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
                <hr>
            {% endif %}
        {% endif %}

        <hr>
        <div class="row mt-2">
            {% for article in articles %}
                <!-- 文章内容 -->
                <div class="col-12">
                    <!-- 文章标签 -->
                    <span>
        {% for tag in article.tags.all %}
            <a href="{% url 'article:article_list' %}?tag={{ tag }}"
               class="badge badge-secondary"
            >
            {{ tag }}
        </a>
        {% endfor %}
         </span>
                    <!-- 标题 -->
                    <h4>
                        <b>
                            <a href="{% url 'article:article_detail' article.id %}"
                               style="color: black;"
                            >
                                {{ article.title }}
                            </a>
                        </b>
                    </h4>
{#                    <!-- 摘要 -->#}
{#                    <div>#}
{#                        <p style="color: gray;">#}
{#                            {{ article.body|slice:'100' }}...#}
{#                        </p>#}
{#                    </div>#}
                    <!-- 注脚 -->
                    <p>
                        <!-- 附加信息 -->
                        <span style="color: green;">
                    <i class="fas fa-eye" style="color: lightskyblue;"></i>
                    {{ article.total_views }} &nbsp;&nbsp;&nbsp;
                </span>
                        <span style="color: blue;">
                    <i class="fas fa-comments" style="color: yellowgreen;"></i>
                    {{ article.comments.count }}&nbsp;&nbsp;&nbsp;
                </span>
                        <span style="color: darkred;">
                    <i class="fas fa-clock" style="color: pink;"></i>
                    {{ article.created|date:'Y-m-d' }}
                </span>
                    </p>
                    <hr>
                </div>
            {% endfor %}

        </div>
    </div>

    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if articles.has_previous %}
                    <a href="?page=1&order={{ order }}&search={{ search }}&tag={{ tag }}" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}&tag={{ tag }}"
                       class="btn btn-secondary"
                    >
                        {{ articles.previous_page_number }}
                    </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}&tag={{ tag }}"
                       class="btn btn-secondary"
                    >
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}&tag={{ tag }}"
                       class="btn btn-success"
                    >
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>

{% endblock content %}

templates/article/update.html
{% extends "base.html" %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action=".">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">文章标题</label>
                        <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                        <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                    </div>
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                        <textarea type="text" class="form-control" id="body" name="body"
                                  rows="12">{{ article.body }}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}