doc/urls.py
from django.urls import path
from . import views

app_name = 'doc'

urlpatterns = [
    path('folder-list/', views.folder_list, name='folder_list'),
    path('folder-create/', views.folder_create, name='folder_create'),
    path('folder-delete/<int:id>/', views.folder_delete, name='folder_delete'),
    path('doc-list/<int:folder>', views.doc_list, name='doc_list'),
    path('doc-add/', views.doc_add, name='doc_add'),
    path('doc-delete/<int:id>/', views.doc_delete, name='doc_delete'),
    path('doc-download/<int:id>', views.doc_download, name='doc_download'),
]

photologue_custom/urls.py
from django.urls import path
from . import views

app_name = 'photologue_custom'

urlpatterns = [
    path('gallery-create/', views.gallery_create, name='gallery_create'),
    path('gallery-delete/<int:id>/', views.gallery_delete, name='gallery_delete'),
    path('photo-add/', views.photo_add, name='photo_add'),
    path('photo-delete/<int:id>/', views.photo_delete, name='photo_delete'),
]

templates/photologue/gallery_create.html
{% extends "base.html" %}
{% block title %} 新建相册 {% endblock title %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action="#">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">相册名称</label>
                        <!-- 文本框 -->
                        <input type="text" class="form-control" id="title" name="title" required>
                    </div>

                    <div class="form-group">
                        <label for="slug">slug(不能为数字)</label>
                        <input type="text"
                               class="form-control col-3"
                               id="slug"
                               name="slug"
                               required
                        >
                    </div>
                    <div class="form-group">
                        <label for="description">相册描述(可选)</label>
                        <!-- 文本区域 -->
                        <textarea type="text" class="form-control" id="description" name="description"
                                  rows="3"></textarea>
                    </div>
                    {#                    <div class="form-group">#}
                    {#                        <label for="is_public">是否公开</label>#}
                    {#                        <input type="checkbox" id="is_public" name="is_public" checked>#}
                    {#                    </div>#}
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">确定</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/photologue/gallery_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ gallery.title }}{% endblock %}

{% block content %}
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <ul class="navbar-nav ml-3">
                <li class="nav-item ml-auto">
                    {% if user.is_superuser %}
                        <a href="#" class= "text-danger" onclick="confirm_delete()">删除相册</a>
                        <form
                                style="display:none;"
                                id="safe_delete"
                                action="{% url 'photologue_custom:gallery_delete' gallery.id %}"
                                method="POST"
                        >
                            {% csrf_token %}
                            <button type="submit">发送</button>
                        </form>
                    {% endif %}
                </li>
            </ul>
        </nav>

        <div class="row col-12">
            <h3 class="page-header">{{ gallery.title }}</h3>
        </div>
        {% if gallery.description %}<p><small>{{ gallery.description|safe }}</small></p>{% endif %}
        {% for photo in gallery.public %}
            <a href="{{ photo.get_absolute_url }}">
                <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
            </a>
        {% endfor %}
        <div><a href="{% url 'photologue:gallery-list' %}"
                class="btn btn-default">{% trans "查看所有相册" %}</a></div>

    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'csrf.js' %}"></script>

    <script>
        function confirm_delete() {
            // 调用layer弹窗组件
            layer.open({
                // 弹窗标题
                title: "确认删除",
                // 正文
                content: "确认删除这个相册吗？",
                // 点击确定按钮后调用的回调函数
                yes: function (index, layero) {
                    $('form#safe_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endblock script %}

templates/photologue/gallery_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}相册{% endblock %}

{% block content %}
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">

            <ul class="navbar-nav ml-3">
                <li class="nav-item ml-auto">
                    {% if user.is_superuser %}
                        <a class="btn btn-primary" href="{% url 'photologue_custom:photo_add' %}">上传照片</a>
                        <a class="btn btn-primary" href="{% url 'photologue_custom:gallery_create' %}">新建相册</a>
                    {% endif %}
                </li>
            </ul>
        </nav>

        {% if object_list %}
            {% for gallery in object_list %}
                <br>
                <div class="row col-12">
                    <a href="{{ gallery.get_absolute_url }}" style="font-size: 200%">{{ gallery.title }}</a>
                </div>
                <div class="muted"><small>{% trans "创建日期" %} {{ gallery.date_added|date:"Y-m-d H:i"}}</small></div>
                {% if gallery.description %}<p><small>{{ gallery.description|safe }}</small></p>{% endif %}
                {% for photo in gallery.sample %}
                    <a href="{{ photo.get_absolute_url }}">
                        <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
                    </a>
                {% endfor %}
                <hr>
            {% endfor %}
        {% else %}
            <div class="row col-12">{% trans "没有相册" %}</div>
        {% endif %}
        {% include "photologue/includes/paginator.html" %}
    </div>
{% endblock %}

templates/photologue/photo_add.html
{% extends "base.html" %}
{% block title %} 上传照片 {% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action="#" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>选择相册</label>
                        <select class="form-control" name="id_gallery">
                            {% for item in gallery %}
                                <option value="{{ item.id }}">{{ item.title }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="image">选择照片</label>
                        <input type="file" class="form-control-file" name="image" id="image"
                               accept="image/gif,image/jpeg,image/jpg,image/png,image/svg" required>
                    </div>

{##}
{#                    <div class="form-group">#}
{#                        <label for="slug">slug(不能为数字)</label>#}
{#                        <input type="text"#}
{#                               class="form-control col-3"#}
{#                               id="slug"#}
{#                               name="slug"#}
{#                               required#}
{#                        >#}
{#                    </div>#}

                    {#                    <div class="form-group">#}
                    {#                        <label for="is_public">是否公开</label>#}
                    {#                        <input type="checkbox" id="is_public" name="is_public" checked>#}
                    {#                    </div>#}
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">确定</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/photologue/photo_detail.html
{% extends "base.html" %}
{% load static %}
{% load photologue_tags i18n %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <ul class="navbar-nav ml-3">
                <li class="nav-item ml-auto">
                    {% if user.is_superuser %}
                        <a href="#" class= "text-danger" onclick="confirm_delete()">删除照片</a>
                        <form
                                style="display:none;"
                                id="safe_delete"
                                action="{% url "photologue_custom:photo_delete" photo.id %}"
                                method="POST"
                        >
                            {% csrf_token %}
                            <button type="submit">发送</button>
                        </form>
                    {% endif %}
                </li>
            </ul>
        </nav>
        <br>
        <div class="row col-lg-12">
            <h3 class="page-header">{{ object.title }}</h3>
        </div>
        <p class="muted"><small>{% trans "上传时间：" %} {{ object.date_added |date:"Y-m-d H:i" }}</small></p>
        <div class="row">
            <div class="col-md-6">
                <a href="{{ object.image.url }}">
                    <img src="{{ object.get_display_url }}" class="thumbnail" alt="{{ object.title }}">
                </a>
            </div>
            <div class="col-md-6">
                {% if object.public_galleries %}
                    <p>{% trans "这张照片在以下相册中" %}:</p>
                    <table>
                        {% for gallery in object.public_galleries %}
                            <tr>
                                {#                                                <td>{% previous_in_gallery object gallery %}</td>#}
                                <td class="text-center"><a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a>
                                </td>
                                {#                                                <td>{% next_in_gallery object gallery %}</td>#}
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'csrf.js' %}"></script>

    <script>
        function confirm_delete() {
            // 调用layer弹窗组件
            layer.open({
                // 弹窗标题
                title: "确认删除",
                // 正文
                content: "确认从所有相册删除这张照片吗？",
                // 点击确定按钮后调用的回调函数
                yes: function (index, layero) {
                    $('form#safe_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endblock script %}