doc/urls.py
from django.urls import path
from . import views

app_name = 'doc'

urlpatterns = [
    path('folder-list/', views.folder_list, name='folder_list'),
    path('folder-create/', views.folder_create, name='folder_create'),
    path('folder-delete/<int:id>/', views.folder_delete, name='folder_delete'),
    path('doc-list/<int:folder>', views.doc_list, name='doc_list'),
    path('doc-add/', views.doc_add, name='doc_add'),
    path('doc-delete/<int:id>/', views.doc_delete, name='doc_delete'),
    path('doc-download/<int:id>', views.doc_download, name='doc_download'),
]

doc/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Folder(models.Model):
    title = models.CharField(max_length=100, unique=True)
    created = models.DateTimeField(default=timezone.now)
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created',)

    def __str__(self):
        return self.title

class Document(models.Model):
    title = models.CharField(max_length=100, unique=True)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)
    is_public = models.BooleanField(default=True)
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created',)
    def __str__(self):
        return self.title

doc/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .models import Folder, Document
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, FileResponse
from .form import FolderPostForm, DocumentPostForm
from django.conf import settings
from django.utils.http import urlquote
from qcloud_cos import CosConfig
from qcloud_cos import CosS3Client
import sys
import logging


# Create your views here.
def folder_list(request):
    folder_list = Folder.objects.all()
    paginator = Paginator(folder_list, 10)
    page = request.GET.get('page')
    folders = paginator.get_page(page)

    context = {
        'folders': folders,
    }

    return render(request, 'doc/folder_list.html', context)


@login_required(login_url='/accounts/login/')
def folder_create(request):
    superuser = User.objects.get(is_superuser=True)
    if request.user != superuser:
        return HttpResponse("权限不够")
    if request.method == "POST":
        folder_post_form = FolderPostForm(data=request.POST)
        if folder_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_folder = folder_post_form.save(commit=False)
            new_folder.save()
            return redirect("doc:folder_list")
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        folder_post_form = FolderPostForm()
        context = {'folder_post_form': folder_post_form}
        return render(request, 'doc/folder_create.html', context)


@login_required(login_url='/accounts/login/')
def folder_delete(request, id):
    superuser = User.objects.get(is_superuser=True)
    if request.user != superuser:
        return HttpResponse("权限不够")
    if request.method == 'POST':
        logging.basicConfig(level=logging.INFO, stream=sys.stdout)
        config = CosConfig(Region=settings.RERION, SecretId=settings.COS_SECRET_ID, SecretKey=settings.COS_SECRET_KEY)
        client = CosS3Client(config)

        docs = Document.objects.filter(folder_id=id)
        #COS删除文件夹下的所有文件
        for doc in docs:
            client.delete_object(
                Bucket='doc-1302212491',
                Key=doc.title
            )
        #删除数据库中的记录
        folder = Folder.objects.get(id=id)
        folder.delete()
        return redirect("doc:folder_list")
    else:
        return HttpResponse("仅允许post请求")


def doc_list(request, folder):
    doc_list = Document.objects.filter(folder=folder)
    paginator = Paginator(doc_list, 10)
    page = request.GET.get('page')
    docs = paginator.get_page(page)

    context = {
        'docs': docs,
    }

    return render(request, 'doc/doc_list.html', context)


@login_required(login_url='/accounts/login/')
def doc_add(request):
    superuser = User.objects.get(is_superuser=True)
    if request.user != superuser:
        return HttpResponse("权限不够")
    if request.method == "POST":
        doc_post_form = DocumentPostForm(request.POST)
        if doc_post_form.is_valid():
            title = request.FILES.get('file').name
            if Document.objects.filter(title=title):
                return HttpResponse("文件名已存在")
            else:
                logging.basicConfig(level=logging.INFO, stream=sys.stdout)
                config = CosConfig(Region=settings.RERION, SecretId=settings.COS_SECRET_ID,
                                   SecretKey=settings.COS_SECRET_KEY)
                client = CosS3Client(config)
                # 保存数据，但暂时不提交到数据库中
                new_doc = doc_post_form.save(commit=False)
                # 在表单给定的文件夹下添加文件
                folder_id = request.POST.get("folder_id")
                folder = Folder.objects.get(id=folder_id)
                new_doc.folder = folder

                new_doc.title = title
                #TODO 大文件上传完后不能正确刷新
                response= client.put_object(
                    Bucket='doc-1302212491',
                    Body=request.FILES.get('file'),
                    Key=new_doc.title
                )
                print(response['ETag'])
                new_doc.save()
                return redirect("doc:folder_list")
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        folders = Folder.objects.all()
        context = {'folders': folders}
        return render(request, 'doc/doc_add.html', context)


@login_required(login_url='/accounts/login/')
def doc_delete(request,id):
    superuser = User.objects.get(is_superuser=True)
    if request.user != superuser:
        return HttpResponse("权限不够")
    if request.method == 'POST':
        logging.basicConfig(level=logging.INFO, stream=sys.stdout)
        config = CosConfig(Region=settings.RERION, SecretId=settings.COS_SECRET_ID, SecretKey=settings.COS_SECRET_KEY)
        client = CosS3Client(config)

        doc = Document.objects.get(id=id)
        folder_id = doc.folder_id
        client.delete_object(
            Bucket='doc-1302212491',
            Key=doc.title
        )

        doc.delete()
        return redirect("doc:doc_list", folder_id)
    else:
        return HttpResponse("仅允许post请求")


@login_required(login_url='/accounts/login/')
def doc_download(request,id):
    if request.method == 'GET':
        logging.basicConfig(level=logging.INFO, stream=sys.stdout)
        config = CosConfig(Region=settings.RERION, SecretId=settings.COS_SECRET_ID, SecretKey=settings.COS_SECRET_KEY)
        client = CosS3Client(config)

        doc = Document.objects.get(id=id)
        cos_response = client.get_object(
            Bucket='doc-1302212491',
            Key=doc.title
        )
        response = FileResponse(cos_response['Body'].get_raw_stream())
        # 指定响应格式为二进制流
        response['Content-Type'] = 'application/octet-stream'
        #TODO 服务端会抛出异常
        #指定下载时的设定 attachment表示以附件下载,urlquote对文件中包含的中文编码
        response['Content-Disposition'] = 'attachment;filename="%s' % (urlquote(doc.title))
        return response
    else:
        return HttpResponse("仅允许post请求")

templates/doc/doc_add.html
{% extends "base.html" %}
{% block title %} 上传文档 {% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action="#" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>选择文件夹</label>
                        <select class="form-control" name="folder_id">
                            {% for folder in folders %}
                                <option value="{{ folder.id }}">{{ folder.title }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="file">选择文件</label>
                        <input type="file" class="form-control-file" name="file" id="file"
                               accept="application/pdf,aplication/zip,text/plain" required>
                    </div>

                    <div class="form-group">
                        <label for="is_public">是否公开</label>
                        <input type="checkbox" id="is_public" name="is_public" checked>
                    </div>

                    <button type="submit" class="btn btn-primary">确定</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/doc/doc_list.html
{% extends "base.html" %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文档
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

    <!-- 定义放置文章标题的div容器 -->
    <div class="container">
        <hr>
        <div class="row mt-2">
            {% for doc in docs %}
                <div class="col-12">
                    <h6>
                        <b>
                            {{ doc.title }}
                            {% if user.is_superuser %}
                                <a href='#' class="ml-5 text-danger" style="float:right"
                                   onclick="confirm_delete()">删除</a>
                                <form
                                        style="display:none;"
                                        id="safe_delete"
                                        action="{% url 'doc:doc_delete' doc.id %}"
                                        method="POST"
                                >
                                    {% csrf_token %}
                                    <button type="submit">发送</button>
                                </form>
                            {% endif %}
                            {% if user.is_superuser or doc.is_public %}
                                <a href="{% url 'doc:doc_download' doc.id %}" class="ml-5" style="float:right">下载</a>
                            {% endif %}

                        </b>
                    </h6>
                    <hr>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if docs.has_previous %}
                    <a href="?page=1" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ docs.previous_page_number }}"
                       class="btn btn-secondary"
                    >
                        {{ docs.previous_page_number }}
                    </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ docs.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if docs.has_next %}
                    <a href="?page={{ docs.next_page_number }}"
                       class="btn btn-secondary"
                    >
                        {{ docs.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ docs.paginator.num_pages }}"
                       class="btn btn-success"
                    >
                        {{ docs.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>

{% endblock content %}




{% block script %}
    <script>
        function confirm_delete() {
            // 调用layer弹窗组件
            layer.open({
                // 弹窗标题
                title: "确认删除",
                // 正文
                content: "确认删除此文件吗？",
                // 点击确定按钮后调用的回调函数
                yes: function (index, layero) {
                    $('form#safe_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endblock script %}

templates/doc/folder_create.html
{% extends "base.html" %}
{% block title %} 新建文件夹 {% endblock title %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-6">
                <br>
                <form method="post" action="#">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">文件夹名称</label>
                        <!-- 文本框 -->
                        <input type="text" class="form-control" id="title" name="title" required>
                    </div>
                    <button type="submit" class="btn btn-primary">确定</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/doc/folder_list.html
{% extends "base.html" %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文件夹
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

    <!-- 定义放置文章标题的div容器 -->
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <ul class="navbar-nav ml-3">
                <li class="nav-item ml-auto">
                    {% if user.is_superuser %}
                        <a class="btn btn-primary" href="{% url 'doc:doc_add' %}">上传文件</a>
                        <a class="btn btn-primary" href="{% url 'doc:folder_create' %}">新建文件夹</a>
                    {% endif %}
                </li>
            </ul>
        </nav>


        <hr>
        <div class="row mt-2">
            {% for folder in folders %}
                <div class="col-12">

                    <b>
                        <a href="{% url 'doc:doc_list' folder.id %}"
                           class="text-muted" style="font-size: 200%"
                        >
                            {{ folder.title }}
                        </a>
                        {% if user.is_superuser %}
                            <a href='#' class="ml-5 text-danger" style="font-size: 150%;float:right" onclick="confirm_delete()">删除</a>
                            <form
                                    style="display:none;"
                                    id="safe_delete"
                                    action="{% url 'doc:folder_delete' folder.id %}"
                                    method="POST"
                            >
                                {% csrf_token %}
                                <button type="submit">发送</button>
                            </form>
                        {% endif %}
                    </b>

                    <hr>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if folders.has_previous %}
                    <a href="?page=1" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ folders.previous_page_number }}"
                       class="btn btn-secondary"
                    >
                        {{ folders.previous_page_number }}
                    </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ folders.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if folders.has_next %}
                    <a href="?page={{ folders.next_page_number }}"
                       class="btn btn-secondary"
                    >
                        {{ folders.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ folders.paginator.num_pages }}"
                       class="btn btn-success"
                    >
                        {{ folders.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>

{% endblock content %}


{% block script %}
    <script>
        function confirm_delete() {
            // 调用layer弹窗组件
            layer.open({
                // 弹窗标题
                title: "确认删除",
                // 正文
                content: "确认删除此文件夹吗？",
                // 点击确定按钮后调用的回调函数
                yes: function (index, layero) {
                    $('form#safe_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endblock script %}